### ISSUE TITLE
Linking on Windows

### ISSUE THREAD

**Issue by 0181532686cf4a31163be0bf3e6bb6732bf** [unbornchikken/boost-lib#13]
Hello again,

I've discovered an issue just opposite to this: https://cmake.org/pipermail/cmake/2008-July/022740.html
While trying to build on Windows, Visual Studio 2015 searches for `boost-system-xxxx` file, instead of `libboost-system-xxxx` (which are created by this package). From http://cpprocks.com/using-cmake-to-build-a-cross-platform-project-with-a-boost-dependency/ I've also got there's a `BOOST_ALL_NO_LIB` define which might solve the problem.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
I solved it in my project by using `add_definitions(-DBOOST_ALL_NO_LIB=1)`

**Comment by unbornchikken** [comment]
Yeah, please remember that CMake.js does just a regular cmake build, you can use all of its features in your lists.
